server:
  port: 8630
spring:
  application:
    name: api-gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

    # config:
    #   import-check:
    #     enabled: false
eureka:
client:
  defaultZone: http://localhost:8761/eureka
  fetchRegistry: true
  registerWithEureka: true